apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer-service
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  strategy: {}
  template:
    metadata:

      labels:
        app: customer-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-order-system-db:3306/ordersystemDB
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: donmba/customer-service:latest
          name: customer-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 8082
  selector:
    app: customer-service
status:
  loadBalancer: {}
