apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - args:
            - -p
            - "3307"
        - env:
            - name: MYSQL_DATABASE
              value:  mysql-db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: mysql-db
          image: mysql:5.7
          name: mysql-db
          ports:
            - containerPort: 3307
          resources: {}
          volumeMounts:
            - mountPath: /data/mysql
              name: mysql-db-claim0
      restartPolicy: Always
      volumes:
        - name: mysql-db-claim0
          persistentVolumeClaim:
            claimName: mysql-db-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3307
  selector:
    app: mysql-db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql-db-claim0
  name: mysql-db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
